### PR TITLE
Add simple ci

### PR DESCRIPTION
**Pull request by pktiuk**
I still think you need at least a basic CI ;)    
Linked with: #137

### CODE REVIEW

**Comment by pktiuk** [comment]
It seems, that something is wrong in your repo config. Builds should already start.    
PR on my repo: https://github.com/pktiuk/rosettadrone/pull/1    

image

**Comment by kripper** [comment]
No clue. Let us know when it works.

**Comment by pktiuk** [comment]
It already works, it is up to you to edit repository settings.

**Comment by pktiuk** [comment]
My repo settings:

image

**Comment by pktiuk** [comment]
It is possible, that due to safety reasons the first commit with workflow is not launched in PR. You can merge this PR now, and then it should launch on master branch and you will get this green checkmark

image

**Comment by kripper** [comment]
Ok, let's see....

**Comment by kripper** [comment]
Hi @The1only, I will need access to the settings page to setup CI.

**Comment by The1only** [comment]
On itBest regardTerje Nilsen9Tek ASNorwayOn 30 Mar 2023, at 16:55, Christopher Pereira ***@***.***> wrote:﻿
Hi @The1only, I will need access to the settings page to setup CI.

**Comment by The1only** [comment]
Any idea How to give you that?Best regardTerje Nilsen9Tek ASNorwayOn 30 Mar 2023, at 16:55, Christopher Pereira ***@***.***> wrote:﻿
Hi @The1only, I will need access to the settings page to setup CI.

**Comment by The1only** [comment]
image

**Comment by The1only** [comment]
The only difference is the Workflow, it that what makes it?

**Comment by pktiuk** [comment]
It seems to work now, a green check appeared next to the name of the latest commit on master

**Comment by pktiuk** [comment]
You can see proper logs here https://github.com/The1only/rosettadrone/actions

**Comment by kripper** [comment]
> Any idea How to give you that?

I'm not sure. Maybe only you can access the settings tab.

Probably the best way is to transfer the repo to the RosettaDrone community github organization:
https://github.com/RosettaDrone

This way, the project will be accesible in https://github.com/RosettaDrone/rosettadrone/

This can be done here:
https://github.com/The1only/rosettadrone/transfer

Use the organization name "RosettaDrone".

And follow instructions on screen.

I just transfered my other related repos to the RosettaDrone org and confirmed that my old personal repo URLs are automatically redirected to the new one.

**Comment by The1only** [comment]
Will doBest regardTerje Nilsen9Tek ASNorwayOn 30 Mar 2023, at 19:13, Christopher Pereira ***@***.***> wrote:﻿

Any idea How to give you that?

I'm not sure. Maybe only you can access the settings tab.
Probably the best way is to transfer the repo to the RosettaDrone community github organization:
https://github.com/RosettaDrone
This way, the project will be accesible in https://github.com/RosettaDrone/rosettadrone/
This can be done here:
https://github.com/The1only/rosettadrone/transfer
Use the organization name "RosettaDrone".
And follow instructions on screen.
I just transfered my other related repos to the RosettaDrone org and confirmed that my old personal repo URLs are automatically redirected to the new one.

**Comment by The1only** [comment]
Feels a bit strange, but the project now got its own life. It’s been a learningfull adventure. Have funn!!!!

**Pull request merged**
