### PR TITLE
Mavic Pro encoding and do_set_motion_velocity fix

### PR DESCRIPTION
**Pull request by gsenkowski**
Hello @The1only i encountered two problems that are fixed with my last two commits.

1. The Mavic Pro requires the old encoding, crashes the app otherwise.

2. In do_set_motion_velocity the mask AND bit must be set for for a valid value, therefore the check must be != 0 instead of == 0.

I tested both changes with a Mavic Pro, i have no other drones at hand right now.

### CODE REVIEW

**Comment by The1only** [comment]
I belive you are wrong, the masks are negative:

Read:  https://mavlink.io/en/messages/common.html#POSITION_TARGET_TYPEMASK

**Comment by The1only** [comment]
Did you test the video fix with a MAVIC PRO and live video on QGC or gStreamer on a PC.
I believe the fix is inclomplete, I will put an update for MAVIC PRO today.

**Comment by gsenkowski** [comment]
> Did you test the video fix with a MAVIC PRO and live video on QGC or gStreamer on a PC.
> I believe the fix is inclomplete, I will put an update for MAVIC PRO today.

This was indeed only intended to keep the app from crashing on startup.



> I belive you are wrong, the masks are negative:
> 
> Read: https://mavlink.io/en/messages/common.html#POSITION_TARGET_TYPEMASK

Ok that makes sense. Then the problem is that in MAVLinkReceiver.java in line 284 the bits are set to ignore the values. Does that mean the MANUAL_CONTROL handling is not fully implemented and intentionally deactivated?

**Comment by The1only** [comment]
We support both Joystick controls and both absolute and relative motion from Mavlink, I use DroneKit and fly complex AI mission with Live video analytics using these commands.

But the bits are quite complex, and must be carefully used. There are 12 bits, and before you use them you should understand their usage. 
We do not support the absolute and relative motion at the same time.

What I always do is set up an Ardupilot SITL on my machine and then run all the control stuff through that to I have verified that it works, and when the behaviour is verified, then I run the RosettaDrone2 in SITL mode.
This way I avoid looking for error two places, as the Ardupilot is quite stabile by now. 

At the moment I do not use TimeLining for absolute motion, so the drone will fly somewhat strange, as the PID in RosettaDrone2 is not tuned.
HOWEVER, all the motion functionality is supposed to work.

The goal is that everything you can do with QGC or DroneKit and a Mavlink based drone, you should be able to do with any DJI-Mobile SDK supported drone.
All the Mavproxy and other Mavlink tools work. 

Terje

**Comment by The1only** [comment]
Two example that works is this:

Again test with Ardupilot SITL first, then with RosettaDrone2...


    # Send a velocity command with +x being NOTRH of the drone.
    def send_global_ned_velocity(self, vx, vy, vz, yaw):
        msg = self.vehicle.message_factory.set_position_target_global_int_encode(
            0,  # time_boot_ms (not used)
            0, 0,  # target system, target component
            mavutil.mavlink.MAV_FRAME_GLOBAL_RELATIVE_ALT_INT,  # frame
            0b0000011111000111,  # type_mask (only speeds enabled)
            0, 0, 0,  # x, y, z positions (not used)
            vx, vy, vz,  # N, E, D velocity in m/s
            0, 0, 0,  # x, y, z acceleration (not supported yet, ignored in GCS_Mavlink)
            0,float(yaw))  # yaw, yaw_rate (not supported yet, ignored in GCS_Mavlink)
        self.vehicle.send_mavlink(msg)
 
    # Send a velocity command with +x being the heading of the drone.
    def send_global_ned_position(self, x, y, z, yaw, speed):
        msg = self.vehicle.message_factory.set_position_target_global_int_encode(
            0,  # time_boot_ms (not used)
            0, 0,  # target system, target component
            mavutil.mavlink.MAV_FRAME_GLOBAL_RELATIVE_ALT_INT,  # frame
            0b0000111111111000,  # type_mask (only position enabled), ignore yaw for now...
            int(x*10000000), int(y*10000000), float(z),  # x, y, z positions (not used)
            speed, speed, 1.0,  # x, y, z velocity in m/s
            0, 0, 0,  # x, y, z acceleration (not supported yet, ignored in GCS_Mavlink)
            float(yaw), 0)  # yaw, yaw_rate (not supported yet, ignored in GCS_Mavlink)
        self.vehicle.send_mavlink(msg)

**Comment by gsenkowski** [comment]
Thanks for your clarifications, this pull request does obviously not contribute anything useful and can be closed. For the bug that i think is still present i will use #32 where the joystick with QGC was mentioned.

**Pull request closed without merging**
